package com.Tiwari.TaskManagement.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;


import java.time.LocalDateTime;


@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class Task {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) //primary key will be generated by database itself
    private Long id;

    @NotBlank(message = "Title is mandatory")
    private String title;

    private String description;


    @Enumerated(EnumType.STRING)
    private TaskStatus status;

    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(nullable = false)
    private LocalDateTime updatedAt;

    @ManyToOne //A single user can have Many tasks
    @JoinColumn(name = "user_id", nullable = false)
    private User assignedTo;

    /*@PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = createdAt;
    }*/

   /* @PreUpdate
    protected void onUpdate() {

        updatedAt = LocalDateTime.now();
    }*/

    //used lombok for Getters and Setters
}
